language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t adiaditiwri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adiaditiwri/docker-react npm run test
